### ISSUE TITLE
Error when attempting to restore

### ISSUE THREAD

**Issue by rzane** [livehelpnow/tds#57]
I'm trying to restore a backup file. The restore succeeds, but TDS seems to be failing to handle the response:

```
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (DBConnection.ConnectionError) client #PID<0.73.0> stopped: ** (FunctionClauseError) no function clause matching in Keyword.delete_key/3
    (elixir) lib/keyword.ex:498: Keyword.delete_key([[%{class: 0, length: 204, line_number: 2, msg_text: "Processed 105008 pages for database 'mydb', file 'mydb_data' on file 1.", number: 4035, proc_name: "", server_name: "589042304e43", state: 1}]], :done, false)
    (elixir) lib/keyword.ex:493: Keyword.put/3
    lib/tds/tokens.ex:381: Tds.Tokens.decode_token/2
    lib/tds/tokens.ex:49: Tds.Tokens.decode_tokens/2
    lib/tds/messages.ex:99: Tds.Messages.parse/4
    lib/tds/protocol.ex:326: Tds.Protocol.new_data/2
    lib/tds/protocol.ex:505: Tds.Protocol.send_param_query/3
    lib/db_connection.ex:958: DBConnection.handle/4
    lib/db_connection.ex:1078: DBConnection.describe_run/5
    lib/db_connection.ex:1199: DBConnection.run_begin/3
    lib/db_connection.ex:1133: DBConnection.run_meter/3
    lib/db_connection.ex:584: DBConnection.prepare_execute/4
    lib/tds.ex:24: Tds.query!/4
```

**Comment by mjaric** [comment]
Unfortunately we didn't yet implemented status message parsing except in case of errors. I hope this is not show stopper for you.

Thanks

**Comment by rzane** [comment]
Okay, that's fine. Do you know of any way I can at least suppress this error? Maybe by silencing the output coming from the database?

**Comment by mjaric** [comment]
I think there is no way to turn off such messages but I will see to make tds handle responses like this

**Comment by mjaric** [comment]
This should be fixed since v2, decoder is rewritten and logs info messages if debug level is turned on
