### ISSUE TITLE
What versions of SQL Server are supported?

### ISSUE THREAD

**Issue by mroach** [livehelpnow/tds#79]
I tried to connect to SQL Server 2000 (8.0) and got this:

```
** (FunctionClauseError) no function clause matching in Tds.Tokens.decode_token/2
    (tds) lib/tds/tokens.ex:98: Tds.Tokens.decode_token(<<253, 0, 0, 0, 0, 0, 0, 0, 0>>, [packetsize: "4096", login_ack: %{program: "Microsoft SQL Server", t_sql_only: true, tds_version: "0x71000001", version: "8.0.7.247"}])
    (tds) lib/tds/tokens.ex:78: Tds.Tokens.decode_tokens/2
    (tds) lib/tds/messages.ex:93: Tds.Messages.parse/4
    (tds) lib/tds/protocol.ex:517: Tds.Protocol.new_data/2
    (tds) lib/tds/protocol.ex:583: Tds.Protocol.login/1
    (tds) lib/tds/protocol.ex:378: Tds.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
State: Tds.Protocol
** (EXIT from #PID<0.475.0>) shell process exited with reason: killed
```

I'm guessing there's an issue connecting to SQL Server 2000, but I couldn't find which versions are officially supported by this package.

**Comment by mjaric** [comment]
Hi @mroach 

I think problem here is that TDS protocol version is hardcoded. I'm not sure exactly how much of work  is to support other, older, versions but should be possible.

**Comment by apcxiii** [comment]
Hello @mroach Can you solve this issue?
