### ISSUE TITLE
Encounter some of errors in test/datetime_test.exs

### ISSUE THREAD

**Issue by 7k8m** [livehelpnow/tds#93]
Errors were as next.
````
  1) test datetime offset (DatetimeTest)
     test/datetime_test.exs:215
     ** (MatchError) no match of right hand side value: ~N[2015-04-08 15:16:23.000000]
     code: Types.decode_datetimeoffset(7, enc)
     stacktrace:
       (tds) lib/tds/types.ex:1789: Tds.Types.decode_datetimeoffset/2
       test/datetime_test.exs:220: (test)

.

  2) test implicit params (DatetimeTest)
     test/datetime_test.exs:274
     ** (CaseClauseError) no case clause matching: {:error, %MatchError{term: ~N[2015-04-08 15:16:23.000000]}}
     code: query("SELECT @n1", [
     stacktrace:
       test/datetime_test.exs:296: (test)



  3) test datetime2 (DatetimeTest)
     test/datetime_test.exs:168
     ** (ArgumentError) cannot convert {{2015, 4, 8}, {131, 56, 23}} to naive datetime, reason: :invalid_time
     code: assert {@date, {131, 56, 23, 0}} == Types.decode_datetime2(0, enc)
     stacktrace:
       (elixir) lib/calendar/naive_datetime.ex:742: NaiveDateTime.from_erl!/3
       test/datetime_test.exs:175: (test)

````

**Comment by 7k8m** [comment]
Related to timezone ... ?

**Comment by 7k8m** [comment]
It seems like some of problem around NaiveDateTime exists ...

**Comment by mjaric** [comment]
@7k8m I fixed this in master. 

BTW, I'm preparing new version that should be used with ecto_sql. Current 2.0.0 wersion in hex is not good so please don't use it
