### ISSUE TITLE
Compiling in Windows

### ISSUE THREAD

**Issue by euphbriggs** [livehelpnow/tds#97]
I'm attempting to compile from the master branch from Windows, but I'm getting the following error when running `mix deps.compile`

```
===> Compiling credentials_obfuscation
==> gettext
Compiling 1 file (.erl)
Compiling 20 files (.ex)
Generated gettext app
===> Compiling ranch
===> Compiling telemetry
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
  c:/Users/ben/Development/rti_processor/deps/parallel_stream/mix.exs:17

==> parallel_stream
Compiling 11 files (.ex)
warning: Stream.chunk/4 is deprecated. Use Stream.chunk_every/4 instead
  lib/parallel_stream/producer.ex:16

Generated parallel_stream app
==> recon
Compiling 6 files (.erl)
Generated recon app
==> csv
Compiling 7 files (.ex)
warning: function CSV.Decoding.Decoder.decode/2 is undefined (module CSV.Decoding.Decoder is not available)
Found at 2 locations:
  lib/csv.ex:103
  lib/csv.ex:187

warning: function CSV.Decoding.Preprocessing.Lines.process/2 is undefined (module CSV.Decoding.Preprocessing.Lines is not available)
  lib/csv.ex:196

Generated csv app
warning: function CSV.Decoding.Preprocessing.None.process/2 is undefined (module CSV.Decoding.Preprocessing.None is not available)
  lib/csv.ex:193

==> jsx
Compiling 9 files (.erl)
Generated jsx app
==> ecto
Compiling 55 files (.ex)
Generated ecto app
==> phoenix_pubsub
Compiling 13 files (.ex)
Generated phoenix_pubsub app
===> Compiling cowlib
===> Compiling cowboy
==> tds
Compiling NIF crate :tds_encoding (native/tds_encoding)...
   Compiling cc v1.0.37
   Compiling libc v0.2.60
   Compiling encoding_index_tests v0.1.4
   Compiling cfg-if v0.1.9
   Compiling rustc-demangle v0.1.15
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling erlang_nif-sys v0.6.4
   Compiling void v1.0.2
   Compiling syn v0.15.39
   Compiling lazy_static v1.3.0
   Compiling unicode-segmentation v1.3.0
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling unreachable v0.1.1
   Compiling heck v0.3.1
   Compiling encoding v0.2.33
error: failed to run custom build command for `erlang_nif-sys v0.6.4`

Caused by:
  process didn't exit successfully: `c:/Users/ben/Development/rti_processor/_build/prod/rustler_crates/tds_encoding\release\build\erlang_nif-sys-432ea327326f7dfc\build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', C:\Users\ben\.cargo\registry\src\github.com-1ecc6299db9ec823\erlang_nif-sys-0.6.4\build.rs:28:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
could not compile dependency :tds, "mix compile" failed. You can recompile this dependency with "mix deps.compile tds", update it with "mix deps.update tds" or clean it with "mix deps.clean tds"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:67: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:40: Mix.Tasks.Compile.All.with_logger_app/1
```

I think it might be related to [this issue](https://github.com/sunny-g/serde_rustler/issues/5), but I'm not sure how to resolve it in Windows.

If I can provide any additional information, please don't hesitate to let me know.

**Comment by mjaric** [comment]
Hi @euphbriggs 

could you please give me elixir and erlang OTP version?

**Comment by euphbriggs** [comment]
Hello @mjaric, thanks for all your help today. You seem to be a very productive person.

After I posted the message in the [Elixir Forum](https://elixirforum.com/t/how-much-work-to-update-an-ecto2-adapter-to-ecto3/18689/19) thread about the success I had with Linux, I realized that I was able to make it work over there by using asdf to install Erlang/OTP 21.

Installing Erlang/OTP 21 in Windows resolved my issue building TDS.

Now, when I run `mix ecto.reset`, I get this error:

```
14:57:47.081 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :rti, Rti.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (Tds.Error) Line 1 (Error 2714): There is already an object named 'schema_migrations' in the database.
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:719: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migrator.ex:635: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql) lib/ecto/migrator.ex:479: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:613: anonymous fn/5 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migrator.ex:612: Ecto.Migrator.migrate/4
    (ecto_sql) lib/ecto/migrator.ex:149: Ecto.Migrator.with_repo/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:117: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:105: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

In the database, I manually dropped all the tables (including `schema_migrations`) before running `mix ecto.reset`. The `schema_migrations` table is created, but none of the migrations are executed. I'm not sure why I'm seeing that error message.

Based on the stacktrace, this issue probably isn't with TDS and is more likely in the "tds-support" branch of your fork of ecto_sql. Would you prefer that I close this issue and we move this conversation somewhere else?

**Comment by euphbriggs** [comment]
To answer your original question. This is what I'm running now:

```
Erlang/OTP 21 [erts-10.2] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.9.4 (compiled with Erlang/OTP 20)
```

**Comment by euphbriggs** [comment]
Moving to: https://github.com/mjaric/ecto_sql/issues/3
